### ISSUE TITLE
RuntimeError: CUDNN_STATUS_MAPPING_ERROR

### ISSUE THREAD

**Issue by lori930** [Mayy1994/RL_segmentation#1]
Hi, when I run train.py, I get the output as below:
```
$ python train.py 
The number of training data: 181
The number of testing data: 78
/home/lanyu/python2-pytorch/local/lib/python2.7/site-packages/torch/serialization.py:367: SourceChangeWarning: source code of class 'FirstP_Net.FirstPNet' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/home/lanyu/python2-pytorch/local/lib/python2.7/site-packages/torch/serialization.py:367: SourceChangeWarning: source code of class 'resnet_skip.SkipResnet50' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/home/lanyu/python2-pytorch/local/lib/python2.7/site-packages/torch/cuda/__init__.py:114: UserWarning: 
    Found GPU0 GeForce RTX 2080 Ti which requires CUDA_VERSION >= 9000 for
     optimal performance and fast startup time, but your PyTorch was compiled
     with CUDA_VERSION 8000. Please install the correct PyTorch binary
     using instructions from http://pytorch.org
    
  warnings.warn(incorrect_binary_warn % (d, name, 9000, CUDA_VERSION))
Building Encoder
Building Encoder
EncoderNet.resnet.conv1.weight
EncoderNet.resnet.bn1.weight
EncoderNet.resnet.bn1.bias
EncoderNet.resnet.layer1.0.conv1.weight
EncoderNet.resnet.layer1.0.bn1.weight
EncoderNet.resnet.layer1.0.bn1.bias
EncoderNet.resnet.layer1.0.conv2.weight
EncoderNet.resnet.layer1.0.bn2.weight
EncoderNet.resnet.layer1.0.bn2.bias
EncoderNet.resnet.layer2.0.conv1.weight
EncoderNet.resnet.layer2.0.bn1.weight
EncoderNet.resnet.layer2.0.bn1.bias
EncoderNet.resnet.layer2.0.conv2.weight
EncoderNet.resnet.layer2.0.bn2.weight
EncoderNet.resnet.layer2.0.bn2.bias
EncoderNet.resnet.layer2.0.downsample.0.weight
EncoderNet.resnet.layer2.0.downsample.1.weight
EncoderNet.resnet.layer2.0.downsample.1.bias
EncoderNet.resnet.layer3.0.conv1.weight
EncoderNet.resnet.layer3.0.bn1.weight
EncoderNet.resnet.layer3.0.bn1.bias
EncoderNet.resnet.layer3.0.conv2.weight
EncoderNet.resnet.layer3.0.bn2.weight
EncoderNet.resnet.layer3.0.bn2.bias
EncoderNet.resnet.layer3.0.downsample.0.weight
EncoderNet.resnet.layer3.0.downsample.1.weight
EncoderNet.resnet.layer3.0.downsample.1.bias
EncoderNet.resnet.layer4.0.conv1.weight
EncoderNet.resnet.layer4.0.bn1.weight
EncoderNet.resnet.layer4.0.bn1.bias
EncoderNet.resnet.layer4.0.conv2.weight
EncoderNet.resnet.layer4.0.bn2.weight
EncoderNet.resnet.layer4.0.bn2.bias
EncoderNet.resnet.layer4.0.downsample.0.weight
EncoderNet.resnet.layer4.0.downsample.1.weight
EncoderNet.resnet.layer4.0.downsample.1.bias
EncoderNet.resnet.fc.weight
EncoderNet.resnet.fc.bias
fc1.weight
fc1.bias
Collecting Experience....
Exception NameError: "global name 'FileNotFoundError' is not defined" in <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7f9b5ebd4190>> ignored
Traceback (most recent call last):
  File "train.py", line 633, in <module>
    main()
  File "train.py", line 219, in main
    _, conv_pixel, _, _, ori_p_pre = FirstP(inputs)
  File "/home/lanyu/python2-pytorch/local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lanyu/ReinforcementLearning/RL_segmentation/FirstP_Net.py", line 157, in forward
    concat_features, final_features = self.resnet_skip(x)
  File "/home/lanyu/python2-pytorch/local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lanyu/ReinforcementLearning/RL_segmentation/resnet_skip.py", line 71, in forward
    conv1_f, layer1_f, layer2_f, layer3_f, layer4_f_ori = self.resnet(x)
  File "/home/lanyu/python2-pytorch/local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lanyu/ReinforcementLearning/RL_segmentation/resnet.py", line 93, in forward
    x = self.conv1(x)
  File "/home/lanyu/python2-pytorch/local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lanyu/python2-pytorch/local/lib/python2.7/site-packages/torch/nn/modules/conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: CUDNN_STATUS_MAPPING_ERROR
```
The running environment: python==2.7, torch==0.4.0, torchvision==0.2.0, cuda==9.0. 
I have searched somewhere else, and was told there are two possible reasons causing `RuntimeError: CUDNN_STATUS_MAPPING_ERROR`, (1) PyTorch version is too high; (2) didn't use `cuda()`. But I think these two are not fit in my case. 

Any help or advice would be very appreciated! Thanks in advance.

**Comment by lori930** [comment]
I figured the problem out. It is because my GPU is 2080Ti, while the PyTorch and cuda version is too low. I have to upgrade the PyTorch to >=1.0.0, and cuda to 10.2. And I used the [https://github.com/Britefury/pytorch-mask-rcnn/tree/refactor-pytorch-1.0](code here) to compile for cuda-support in PyTorch 1.0.0.
